name: Build Game for Android
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flag: [ONLY_ARMV7, ONLY_ARM64, UNIVERSAL]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.4

      - name: Install Libraries
        run: |
          haxelib install hxcpp
          haxelib install lime 7.8.0
          haxelib install openfl
          haxelib install flixel 4.8.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-tools
          haxelib install flixel-addons 2.11.0
          haxelib install hscript
          haxelib install newgrounds 1.3.0
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android -D ${{matrix.flag}}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-${{matrix.flag}}
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: error
