name: Build Game for Android
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flag: [ONLY_ARMV7, ONLY_ARM64, UNIVERSAL]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: | 
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib --never install flixel 4.9.0 --quiet
          haxelib run lime setup --quiet
          haxelib install hscript
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install newgrounds
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib git polymod https://github.com/larsiusprime/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-webm https://github.com/Sirox228/extension-webm --quiet
          haxelib git linc_luajit https://github.com/Daninnocent/linc_luajit.git --quiet
          haxelib install actuate
          haxelib list

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android -D ${{matrix.flag}}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-${{matrix.flag}}
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: error
